### ISSUE TITLE
Great addition to Ecto

### ISSUE THREAD

**Issue by olafura** [nathanjohnson320/Ecto-Generator#1]
Hi, I'm wondering if you would merge this into Ecto. I'm not a developer working on Ecto I'm just interested in this functionality. Other frameworks seem to have similar features.

Maybe something that queries to columns and does the matching with the supported types in Ecto and then generator which would use this.

With that kind of approach it should be possible to integrate it with Phoenix.

**Comment by nathanjohnson320** [comment]
I think they might be open to adding this sort of functionality. It wouldn't be too difficult to make this into a mix task which could integrate fairly easily.

I can at the very least open an issue over on ecto and see if they're open to worst they can do say is no.

**Comment by nathanjohnson320** [comment]
Closed given the response from 1092

**Comment by olafura** [comment]
Cool, sounds like a plan. I'm wondering if you could add an licence. I'll try helping out ;)

**Comment by nathanjohnson320** [comment]
Allrighty, I added one so feel free to help out :+1:
